# Programming Assignment 5
---
**Author:** Savannah Gripshover 
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

### Problem 1 - Language Translator

In [2]:
translation_dict = {
    'chair': 'stoel',
    'man': 'man',
    'woman': 'vrouw',
    'bear': 'beer',
    'cat': 'kat',
    'dog': 'hond',
}

def translate_to_dutch(word):
    if word.lower() in translation_dict:
        return translation_dict[word.lower()]
    else:
        return f"The Dutch word for {word.upper()} is not in this dictionary."

print("Enter the word you want to translate from English to Dutch (enter 0 to stop):")
while True:
    word = input()
    if word == '0':
        break
    else:
        translation = translate_to_dutch(word)
        print(translation)

Enter the word you want to translate from English to Dutch (enter 0 to stop):


 0


### Problem 2 - Training Morse Code

In [4]:
morse_code_dict = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....',
    'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.',
    'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
    'Y': '-.--', 'Z': '--..',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....',
    '6': '-....', '7': '--...', '8': '---..', '9': '----.',
}

In [5]:
def translate_to_morse(sentence):
    morse_translation = ""
    for char in sentence:
        if char.upper() in morse_code_dict:
            morse_translation += morse_code_dict[char.upper()] + " "
        elif char == ' ':
            morse_translation += "/ "
    return morse_translation.strip()

In [6]:
print("Enter a sentence to translate to Morse code (enter 'q' to quit):")
while True:
    sentence = input().strip()
    if sentence.lower() == 'q':
        break
    else:
        morse_translation = translate_to_morse(sentence)
        print("Morse Code Translation:", morse_translation)

Enter a sentence to translate to Morse code (enter 'q' to quit):


 hello


Morse Code Translation: .... . .-.. .-.. ---


 beep boop


Morse Code Translation: -... . . .--. / -... --- --- .--.


 q


BUSA 103, 203, 301, and 305### Problem 3 - Comparing Majors/Minors

In [7]:
cs_minor_courses = {'CS 100', 'CS 131', 'CS 215', 'CS400'}
ba_minor_courses = {'BUSA 103', 'BUSA 203', 'BUSA 301', 'BUSA 305', 'ACCT 101', 'ECON 110', 'FINA 315', 'MATH 125' }
ba_analytics_minor_courses = {'BUSA 103', 'BUSA 245', 'BUSA 346', 'CS 150', 'DS 160', 'DS 300'}
ds_major_courses = {'BUSA 103', 'BUSA 245', 'BUSA 346', 'CS 150', 'DS 160', 'DS 300', 'DS 450', 'MATH 205', 'MATH 215', 'MATH 430', 'ECON 410'}

overlap_courses = ba_minor_courses.intersection(ba_analytics_minor_courses)
print("Overlapping courses between Business Administration and Business Analytics minors:", overlap_courses)

all_courses_required = ba_minor_courses.union(cs_minor_courses)
print("All courses required for minoring in Business Administration and Computer Science:", all_courses_required)

ba_not_in_analytics = ba_minor_courses.difference(ba_analytics_minor_courses)
print("Courses in Business Administration minor but not in Business Analytics minor:", ba_not_in_analytics)

cs_ds_overlap = cs_minor_courses.intersection(ds_major_courses)
print("Overlapping courses between Computer Science major and Data Science major:", cs_ds_overlap)

ba_analytics_subsumed = ba_analytics_minor_courses.issubset(ds_major_courses)
print("Is Business Analytics minor completely subsumed by Data Science major?", ba_analytics_subsumed)

Overlapping courses between Business Administration and Business Analytics minors: {'BUSA 103'}
All courses required for minoring in Business Administration and Computer Science: {'CS 100', 'CS 215', 'BUSA 301', 'FINA 315', 'MATH 125', 'BUSA 305', 'ECON 110', 'CS400', 'BUSA 203', 'CS 131', 'ACCT 101', 'BUSA 103'}
Courses in Business Administration minor but not in Business Analytics minor: {'BUSA 301', 'FINA 315', 'MATH 125', 'BUSA 305', 'ECON 110', 'BUSA 203', 'ACCT 101'}
Overlapping courses between Computer Science major and Data Science major: set()
Is Business Analytics minor completely subsumed by Data Science major? True


### Problem 4 - Working with NumPy

In [8]:
import numpy as np

In [9]:
array1 = np.random.randint(0, 21, size=(5, 5))
array2 = np.random.randint(0, 21, size=(5, 5))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

matrix_product = np.matmul(array1, array2)
dot_product = np.dot(array1.flatten(), array2.flatten())

print("\nMatrix Product:")
print(matrix_product)
print("\nDot Product:")
print(dot_product)

Array 1:
[[ 8 14 16 10  8]
 [ 9 11 12  7  1]
 [17 19 15 15 15]
 [ 4  9 12 15 17]
 [12  0  7  0  5]]

Array 2:
[[ 5  0  5 18 13]
 [14 12 19 13  0]
 [16  1  3 20 11]
 [11 17  0  5 11]
 [ 5  1  6 14  1]]

Matrix Product:
[[ 642  362  402  808  398]
 [ 473  264  296  594  327]
 [ 831  513  581 1138  566]
 [ 588  392  329  742  366]
 [ 197   12  111  426  238]]

Dot Product:
2348


In [10]:
det_array1 = np.linalg.det(array1)
det_array2 = np.linalg.det(array2)
inv_array1 = np.linalg.inv(array1)
inv_array2 = np.linalg.inv(array2)

print("\nDeterminant of Array 1:", det_array1)
print("Inverse of Array 1:")
print(inv_array1)
print("\nDeterminant of Array 2:", det_array2)
print("Inverse of Array 2:")
print(inv_array2)


Determinant of Array 1: 78520.00000000013
Inverse of Array 1:
[[-0.11617422  0.07666836  0.04080489  0.00086602  0.04518594]
 [ 0.14214213 -0.14149261  0.08250127 -0.11123281 -0.06844116]
 [ 0.11146205  0.00866021 -0.09505858  0.01670912  0.04829343]
 [-0.28261589  0.27980132 -0.02417219  0.1486755  -0.03675497]
 [ 0.12277127 -0.19612837  0.03515028 -0.02547122  0.02394294]]

Determinant of Array 2: 394345.0000000005
Inverse of Array 2:
[[-0.05978521  0.02492488  0.09640036 -0.01871711 -0.07730794]
 [-0.01684566 -0.01600882 -0.05652411  0.06797855  0.09299471]
 [ 0.06180882  0.07153381 -0.02051503 -0.04334022 -0.1011069 ]
 [-0.01040206 -0.03969113 -0.02165616  0.02075087  0.14518505]
 [ 0.09054762  0.01785746  0.00079879 -0.00486376 -0.13240437]]
